package analytics

var countryCodeToContinent = map[string]string{
	"BT": "Asia",
	"KG": "Asia",
	"NP": "Asia",
	"AE": "Asia",
	"CX": "Asia",
	"AF": "Asia",
	"CN": "Asia",
	"KR": "Asia",
	"MO": "Asia",
	"MM": "Asia",
	"TH": "Asia",
	"BD": "Asia",
	"TR": "Asia",
	"IN": "Asia",
	"OM": "Asia",
	"IQ": "Asia",
	"VN": "Asia",
	"LA": "Asia",
	"MV": "Asia",
	"PK": "Asia",
	"IL": "Asia",
	"PH": "Asia",
	"AZ": "Asia",
	"IR": "Asia",
	"MN": "Asia",
	"TL": "Asia",
	"SA": "Asia",
	"AM": "Asia",
	"SG": "Asia",
	"TW": "Asia",
	"UZ": "Asia",
	"JP": "Asia",
	"KP": "Asia",
	"KH": "Asia",
	"KZ": "Asia",
	"BH": "Asia",
	"BN": "Asia",
	"CC": "Asia",
	"TJ": "Asia",
	"GE": "Asia",
	"TM": "Asia",
	"JO": "Asia",
	"LK": "Asia",
	"QA": "Asia",
	"MY": "Asia",
	"ID": "Asia",
	"SY": "Asia",
	"LB": "Asia",
	"YE": "Asia",
	"IO": "Asia",
	"HK": "Asia",
	"KW": "Asia",
	"PS": "Asia",
	"BI": "Africa",
	"GA": "Africa",
	"SL": "Africa",
	"GN": "Africa",
	"LY": "Africa",
	"MZ": "Africa",
	"UG": "Africa",
	"SS": "Africa",
	"ET": "Africa",
	"ZA": "Africa",
	"CF": "Africa",
	"SC": "Africa",
	"DZ": "Africa",
	"ZW": "Africa",
	"LR": "Africa",
	"NE": "Africa",
	"GW": "Africa",
	"MW": "Africa",
	"RW": "Africa",
	"SD": "Africa",
	"BJ": "Africa",
	"CD": "Africa",
	"TN": "Africa",
	"YT": "Africa",
	"AO": "Africa",
	"CV": "Africa",
	"RE": "Africa",
	"CG": "Africa",
	"LS": "Africa",
	"CM": "Africa",
	"MR": "Africa",
	"TZ": "Africa",
	"EG": "Africa",
	"DJ": "Africa",
	"TG": "Africa",
	"ER": "Africa",
	"NA": "Africa",
	"GM": "Africa",
	"SZ": "Africa",
	"TD": "Africa",
	"KM": "Africa",
	"ST": "Africa",
	"GH": "Africa",
	"GQ": "Africa",
	"ML": "Africa",
	"CI": "Africa",
	"MU": "Africa",
	"SO": "Africa",
	"BF": "Africa",
	"NG": "Africa",
	"SN": "Africa",
	"EH": "Africa",
	"MA": "Africa",
	"SH": "Africa",
	"MG": "Africa",
	"BW": "Africa",
	"KE": "Africa",
	"ZM": "Africa",
	"CZ": "Europe",
	"IT": "Europe",
	"MC": "Europe",
	"AL": "Europe",
	"BE": "Europe",
	"HR": "Europe",
	"LT": "Europe",
	"SK": "Europe",
	"BG": "Europe",
	"HU": "Europe",
	"FO": "Europe",
	"SI": "Europe",
	"EE": "Europe",
	"AX": "Europe",
	"FI": "Europe",
	"IS": "Europe",
	"JE": "Europe",
	"NL": "Europe",
	"SJ": "Europe",
	"RS": "Europe",
	"DK": "Europe",
	"PL": "Europe",
	"MK": "Europe",
	"VA": "Europe",
	"UA": "Europe",
	"BA": "Europe",
	"AT": "Europe",
	"AD": "Europe",
	"CH": "Europe",
	"GG": "Europe",
	"RU": "Europe",
	"DE": "Europe",
	"GB": "Europe",
	"ME": "Europe",
	"GR": "Europe",
	"BY": "Europe",
	"LV": "Europe",
	"NO": "Europe",
	"RO": "Europe",
	"ES": "Europe",
	"IM": "Europe",
	"SM": "Europe",
	"PT": "Europe",
	"IE": "Europe",
	"MD": "Europe",
	"SE": "Europe",
	"MT": "Europe",
	"LI": "Europe",
	"CY": "Europe",
	"GI": "Europe",
	"FR": "Europe",
	"LU": "Europe",
	"SB": "Oceania",
	"GU": "Oceania",
	"PG": "Oceania",
	"FM": "Oceania",
	"AU": "Oceania",
	"NC": "Oceania",
	"UM": "Oceania",
	"PF": "Oceania",
	"TO": "Oceania",
	"NZ": "Oceania",
	"MH": "Oceania",
	"NF": "Oceania",
	"WS": "Oceania",
	"NU": "Oceania",
	"PW": "Oceania",
	"PN": "Oceania",
	"KI": "Oceania",
	"TV": "Oceania",
	"TK": "Oceania",
	"FJ": "Oceania",
	"AS": "Oceania",
	"WF": "Oceania",
	"NR": "Oceania",
	"CK": "Oceania",
	"VU": "Oceania",
	"MP": "Oceania",
	"TF": "Antarctica",
	"HM": "Antarctica",
	"BV": "Antarctica",
	"FQ": "Antarctica",
	"AQ": "Antarctica",
	"CW": "North America",
	"TC": "North America",
	"HN": "North America",
	"PA": "North America",
	"BQ": "North America",
	"HT": "North America",
	"VG": "North America",
	"MQ": "North America",
	"BL": "North America",
	"MF": "North America",
	"BZ": "North America",
	"VI": "North America",
	"GL": "North America",
	"GP": "North America",
	"MS": "North America",
	"VC": "North America",
	"US": "North America",
	"AG": "North America",
	"SX": "North America",
	"AN": "North America",
	"BS": "North America",
	"PR": "North America",
	"LC": "North America",
	"BM": "North America",
	"DM": "North America",
	"AW": "North America",
	"JM": "North America",
	"CA": "North America",
	"SV": "North America",
	"KY": "North America",
	"CR": "North America",
	"DO": "North America",
	"NI": "North America",
	"PM": "North America",
	"AI": "North America",
	"GT": "North America",
	"MX": "North America",
	"TT": "North America",
	"KN": "North America",
	"CU": "North America",
	"GD": "North America",
	"BB": "North America",
	"AR": "South America",
	"CO": "South America",
	"BO": "South America",
	"GS": "South America",
	"CL": "South America",
	"EC": "South America",
	"PE": "South America",
	"UY": "South America",
	"FK": "South America",
	"SR": "South America",
	"VE": "South America",
	"GY": "South America",
	"GF": "South America",
	"PY": "South America",
	"BR": "South America",
}

// GetContinent resolves the continent name from the country code.
// We don't have Continent Name in our Geo DB and country codes do not change very often,
// so mapping it with constant values should be good enough.
func GetContinent(countryCode string) string {
	if c, ok := countryCodeToContinent[countryCode]; ok {
		return c
	}
	return ""
}
