type: "object"
properties:
  session_id:
    type: "string"
  playback_id:
    type: "string"
  protocol:
    type: "string"
  page_url:
    type: "string"
  source_url:
    type: "string"
  player:
    type: "string"
  user_agent:
    type: "string"
  uid:
    type: "string"
  events:
    type: "array"
    items:
      - type: "object"
        properties:
          type:
            type: "string"
          timestamp:
            type: "integer"
          errors:
            type: "integer"
          playtime_ms:
            type: "integer"
          ttff_ms:
            type: "integer"
          preload_time_ms:
            type: "integer"
          buffer_ms:
            type: "integer"
          autoplay_status:
            type: "string"
          error_message:
            type: "string"
        required:
          - type
          - timestamp
required:
  - session_id
  - playback_id
  - protocol
  - page_url
  - source_url
  - player
  - user_agent
  - events
