type: "object"
properties:
  source_location:
    type: "string"
  callback_url:
    type: "string"
  accessToken:
    type: "string"
  transcodeAPIUrl:
    type: "string"
  manifestID:
    type: "string"
  streamID:
    type: "string"
  sessionID:
    type: "string"
  streamKey:
    type: "string"
  presets:
    type: "array"
    items:
      type: "string"
  objectStore:
    type: "string"
  recordObjectStore:
    type: "string"
  recordObjectStoreUrl:
    type: "string"
  profiles:
    type: "array"
    items:
      type: "object"
      properties:
        name:
          type: "string"
        width:
          type: "integer"
        height:
          type: "integer"
        bitrate:
          type: "integer"
        fps:
          type: "integer"
        fpsDen:
          type: "integer"
        profile:
          type: "string"
        gop:
          type: "string"
        encoder:
          type: "string"
        colorDepth:
          type: "integer"
        chromaFormat:
          type: "integer"
      additionalProperties: false
      required:
      -  "name"
      - "width"
      -  "height"
      - "bitrate"
  previousSessions:
    type: "array"
    items:
      type: "string"
  detection:
    type: "object"
    properties:
      freq:
        type: "integer"
      sampleRate:
        type: "integer"
      sceneClassification:
        type: "array"
        items:
          type: "object"
          properties:
            name:
              type: "string"
          additionalProperties: false
          required:
          - "name"
    additionalProperties: false
    required:
    - "freq"
    - "sampleRate"
  verificationFreq:
    type: "integer"
additionalProperties: false
required:
- "source_location"
- "callback_url"
- "manifestID"
- "profiles"
- "verificationFreq"
